## DATA ENCODING
1. Nominal/OHE
2. Label and Ordinal
3. Target Guided Ordinal Encoding

## OHE
One Hot Encoding is a method for converting categorical variables into a binary format. It creates new columns for each category where 1 means the category is present and 0 means it is not. The primary purpose of One Hot Encoding is to ensure that categorical data can be effectively used in machine learning models.

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
## Create a simple data frame
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [ ]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [ ]:
## we create an instance of one hot encoder

encoder = OneHotEncoder()

In [ ]:
## Perform fit and then transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [ ]:
import pandas as pd
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [ ]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
pd.concat([df,encoded_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0