## Pandas

WHAT IS PANDAS?

Pandas is a Python library used for working with data sets.
It has functions for analyzing, cleaning, exploring, and manipulating data.
The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.


WHY USE PANDAS?

Pandas allows us to analyze big data and make conclusions based on statistical theories.
Pandas can clean messy data sets, and make them readable and relevant.
Relevant data is very important in data science.


WHAT CAN PANDAS DO?

Pandas gives you answers about the data. Like:

Is there a correlation between two or more columns?

What is average value?

Max value?

Min value?

Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

In [ ]:
import pandas as pd

## SERIES
Pandas Series is a one-dimensional labeled array that can hold data of any type (integer, float, string, Python objects, etc.). It is similar to a column in an Excel spreadsheet or a database table. In this article we will study Pandas Series a powerful one-dimensional data structure in Python.

In [ ]:
import pandas as pd
data=[1,2,3,4,5]
series = pd.Series(data)
print("Series \n",series)
print(type(series))

In [ ]:
## Create a series from dictionary

data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

In [ ]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

## Data Frame
Pandas DataFrame is two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. Pandas DataFrame consists of three principal components, the data, rows, and columns.

In [ ]:
## Create a data frame from dictionary from list

data = {
    'Name' : ['Wick','John','Jack'],
    'Age' : [25,30,25],
    'City' : ['Banglore','Florida','New York']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

In [ ]:
## Create a data frame from the list of dictionaries

data = [
    {'Name': "Wick" , 'age': 32, 'City' : 'Banglore'},
    {'Name': "John" , 'age': 34, 'City' : 'Florida'},
    {'Name': "Jack" , 'age': 35, 'City' : 'New York'},
    {'Name': "Bappy" , 'age': 37, 'City' : 'Banglore'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

## Accessing Data

In [ ]:
data = {
    'Name' : ['Wick','John','Jack'],
    'Age' : [25,30,25],
    'City' : ['Banglore','Florida','New York']
}


df = pd.DataFrame(data)

df['Name']

In [ ]:
df.loc[0]

In [ ]:
df.iloc[0][2]

In [ ]:
df

In [ ]:
## Accessing a specified element

print(df.at[1,'Age'])
print(df.at[2,'Age'])

In [ ]:
### Accessing a specified element with iat

print(df.iat[2,2])

## DATA MANIPULATION WITH DATA FRAMES

In [65]:
data = {
    'Name' : ['Wick','John','Jack'],
    'Age' : [25,30,25],
    'City' : ['Banglore','Florida','New York']
}


df = pd.DataFrame(data)
df

   Name  Age      City
0  Wick   25  Banglore
1  John   30   Florida
2  Jack   25  New York

In [66]:
df

   Name  Age      City
0  Wick   25  Banglore
1  John   30   Florida
2  Jack   25  New York

In [67]:
## adding another column
df['Salary'] = [50000,60000,70000]
df

   Name  Age      City  Salary
0  Wick   25  Banglore   50000
1  John   30   Florida   60000
2  Jack   25  New York   70000

In [ ]:
df.drop('Salary',axis=1)
##To remove column we used axis = 1 as python initially checks row
## Drop is not a permanent operation it usually not saveshecnce fopr that we have to add inplace=True

   Name  Age      City
0  Wick   25  Banglore
1  John   30   Florida
2  Jack   25  New York

In [70]:
df

   Name  Age      City  Salary
0  Wick   25  Banglore   50000
1  John   30   Florida   60000
2  Jack   25  New York   70000

In [71]:
df.drop('Salary',axis=1,inplace=True)

##This is The proper method to remove a column
df

   Name  Age      City
0  Wick   25  Banglore
1  John   30   Florida
2  Jack   25  New York

In [72]:
#Add age to column

df['Age']=df['Age']+1
df

   Name  Age      City
0  Wick   26  Banglore
1  John   31   Florida
2  Jack   26  New York

In [ ]:
df.drop(0,inplace=True)

In [75]:
df

   Name  Age      City
1  John   31   Florida
2  Jack   26  New York