## DATA MANIPULATION WITH PANDAS AND NUMPY

In Machine Learning, the model requires a dataset to operate, i.e. to train and test. But data doesn’t come fully prepared and ready to use. There are discrepancies like Nan/ Null / NA values in many rows and columns. Sometimes the data set also contains some of the rows and columns which are not even required in the operation of our model. In such conditions, it requires proper cleaning and modification of the data set to make it an efficient input for our model. We achieve that by practicing Data Wrangling before giving data input to the model.

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("task.csv")
## Fetch first 5 rows
df.head(5)

,Date,Career Progress,Career Reflection,Career Action Plan,Self-care Progress,Self-care Reflection,Self-care Action Plan,Future Planning Progress,Future Planning Reflection,Future Planning Action Plan
0,21-Jan-25,Worked on DSA practice,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for DSA practice r...,Completed Meditation,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Meditation,Completed Internship research,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Internship research
1,22-Jan-25,Worked on Python project,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Python project...,Completed Yoga session,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Yoga session,Completed University shortlist,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for University shortlist
2,23-Jan-25,Worked on AI fundamentals,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for AI fundamental...,Completed Jogging,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Jogging,Completed Scholarship options,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Scholarship options
3,24-Jan-25,Worked on LeetCode problems,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for LeetCode probl...,Completed Journaling,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Journaling,Completed Resume update,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Resume update
4,25-Jan-25,Worked on Prompt engineering,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Prompt enginee...,Completed Healthy meal prep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Healthy meal...,Completed Networking outreach,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Networking outreach

In [6]:
## Fetch last 5 rows
df.tail(5)

,Date,Career Progress,Career Reflection,Career Action Plan,Self-care Progress,Self-care Reflection,Self-care Action Plan,Future Planning Progress,Future Planning Reflection,Future Planning Action Plan
27,17-Feb-25,Worked on LeetCode problems,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for LeetCode probl...,Completed Journaling,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Journaling,Completed Resume update,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Resume update
28,18-Feb-25,Worked on Prompt engineering,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Prompt enginee...,Completed Healthy meal prep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Healthy meal...,Completed Networking outreach,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Networking outreach
29,19-Feb-25,Worked on Generative AI course,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Generative AI ...,Completed Adequate sleep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Adequate sleep,Completed Skill gap analysis,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Skill gap analysis
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.dtypes

Date                           object
Career Progress                object
Career Reflection              object
Career Action Plan             object
Self-care Progress             object
Self-care Reflection           object
Self-care Action Plan          object
Future Planning Progress       object
Future Planning Reflection     object
Future Planning Action Plan    object
dtype: object

## Handling missing values

In [12]:
df.isnull()

,Date,Career Progress,Career Reflection,Career Action Plan,Self-care Progress,Self-care Reflection,Self-care Action Plan,Future Planning Progress,Future Planning Reflection,Future Planning Action Plan
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False
30,True,True,True,True,True,True,True,True,True,True
31,True,True,True,True,True,True,True,True,True,True

In [17]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31     True
dtype: bool

In [18]:
df.isnull().sum()

Date                           2
Career Progress                2
Career Reflection              2
Career Action Plan             2
Self-care Progress             2
Self-care Reflection           2
Self-care Action Plan          2
Future Planning Progress       2
Future Planning Reflection     2
Future Planning Action Plan    2
dtype: int64

In [ ]:
df_filled=df.fillna(0)

,Date,Career Progress,Career Reflection,Career Action Plan,Self-care Progress,Self-care Reflection,Self-care Action Plan,Future Planning Progress,Future Planning Reflection,Future Planning Action Plan
0,21-Jan-25,Worked on DSA practice,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for DSA practice r...,Completed Meditation,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Meditation,Completed Internship research,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Internship research
1,22-Jan-25,Worked on Python project,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Python project...,Completed Yoga session,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Yoga session,Completed University shortlist,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for University shortlist
2,23-Jan-25,Worked on AI fundamentals,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for AI fundamental...,Completed Jogging,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Jogging,Completed Scholarship options,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Scholarship options
3,24-Jan-25,Worked on LeetCode problems,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for LeetCode probl...,Completed Journaling,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Journaling,Completed Resume update,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Resume update
4,25-Jan-25,Worked on Prompt engineering,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Prompt enginee...,Completed Healthy meal prep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Healthy meal...,Completed Networking outreach,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Networking outreach
5,26-Jan-25,Worked on Generative AI course,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Generative AI ...,Completed Adequate sleep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Adequate sleep,Completed Skill gap analysis,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Skill gap analysis
6,27-Jan-25,Worked on DSA practice,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for DSA practice r...,Completed Meditation,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Meditation,Completed Internship research,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Internship research
7,28-Jan-25,Worked on Python project,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Python project...,Completed Yoga session,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Yoga session,Completed University shortlist,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for University shortlist
8,29-Jan-25,Worked on AI fundamentals,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for AI fundamental...,Completed Jogging,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Jogging,Completed Scholarship options,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Scholarship options
9,30-Jan-25,Worked on LeetCode problems,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for LeetCode probl...,Completed Journaling,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Journaling,Completed Resume update,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Resume update
10,31-Jan-25,Worked on Prompt engineering,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Prompt enginee...,Completed Healthy meal prep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Healthy meal...,Completed Networking outreach,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Networking outreach
11,01-Feb-25,Worked on Generative AI course,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Generative AI ...,Completed Adequate sleep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Adequate sleep,Completed Skill gap analysis,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Skill gap analysis
12,02-Feb-25,Worked on DSA practice,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for DSA practice r...,Completed Meditation,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Meditation,Completed Internship research,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Internship research
13,03-Feb-25,Worked on Python project,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Python project...,Completed Yoga session,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Yoga session,Completed University shortlist,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for University shortlist
14,04-Feb-25,Worked on AI fundamentals,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for AI fundamental...,Completed Jogging,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Jogging,Completed Scholarship options,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Scholarship options
15,05-Feb-25,Worked on LeetCode problems,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for LeetCode probl...,Completed Journaling,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Journaling,Completed Resume update,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Resume update
16,06-Feb-25,Worked on Prompt engineering,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Prompt enginee...,Completed Healthy meal prep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Healthy meal...,Completed Networking outreach,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Networking outreach
17,07-Feb-25,Worked on Generative AI course,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Generative AI ...,Completed Adequate sleep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Adequate sleep,Completed Skill gap analysis,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Skill gap analysis
18,08-Feb-25,Worked on DSA practice,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for DSA practice r...,Completed Meditation,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Meditation,Completed Internship research,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Internship research
19,09-Feb-25,Worked on Python project,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Python project...,Completed Yoga session,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Yoga session,Completed University shortlist,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for University shortlist
20,10-Feb-25,Worked on AI fundamentals,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for AI fundamental...,Completed Jogging,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Jogging,Completed Scholarship options,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Scholarship options
21,11-Feb-25,Worked on LeetCode problems,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for LeetCode probl...,Completed Journaling,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Journaling,Completed Resume update,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Resume update
22,12-Feb-25,Worked on Prompt engineering,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Prompt enginee...,Completed Healthy meal prep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Healthy meal...,Completed Networking outreach,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Networking outreach
23,13-Feb-25,Worked on Generative AI course,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Generative AI ...,Completed Adequate sleep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Adequate sleep,Completed Skill gap analysis,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Skill gap analysis
24,14-Feb-25,Worked on DSA practice,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for DSA practice r...,Completed Meditation,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Meditation,Completed Internship research,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Internship research
25,15-Feb-25,Worked on Python project,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Python project...,Completed Yoga session,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Yoga session,Completed University shortlist,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for University shortlist
26,16-Feb-25,Worked on AI fundamentals,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for AI fundamental...,Completed Jogging,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Jogging,Completed Scholarship options,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Scholarship options
27,17-Feb-25,Worked on LeetCode problems,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for LeetCode probl...,Completed Journaling,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Journaling,Completed Resume update,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Resume update
28,18-Feb-25,Worked on Prompt engineering,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Prompt enginee...,Completed Healthy meal prep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Healthy meal...,Completed Networking outreach,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Networking outreach
29,19-Feb-25,Worked on Generative AI course,Went well: made progress; Challenge: time mana...,Plan: allocate focused slot for Generative AI ...,Completed Adequate sleep,Went well: felt restorative; Challenge: stayin...,Plan: set reminder for tomorrow's Adequate sleep,Completed Skill gap analysis,Went well: gathered info; Challenge: decision ...,Plan: list pros/cons for Skill gap analysis
30,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0

## TAKING A NEW CSV FILE

In [26]:
d_frame = pd.read_csv("Sales.csv")
d_frame

,Order No,Order Date,Customer Name,Ship Date,Retail Price (USD),Order Quantity,Tax (USD),Total (USD)
0,1001,01-01-2024,John Smith,01-03-2024,49.99,2,9.998,109.978
1,1002,01-01-2024,Jane Doe,01-04-2024,29.99,1,2.999,32.989
2,1003,01-02-2024,Michael Johnson,01-07-2024,99.99,3,29.997,329.967
3,1004,01-02-2024,Emily Brown,01-03-2024,19.99,4,7.996,87.956
4,1005,01-03-2024,David Wilson,01-08-2024,149.99,1,14.999,164.989
...,...,...,...,...,...,...,...,...
65,1066,02-02-2024,Sarah Gonzalez,02-06-2024,79.99,2,15.998,175.978
66,1067,02-03-2024,Matthew Smith,02-06-2024,49.99,3,14.997,164.967
67,1068,02-04-2024,Emily Johnson,02-05-2024,129.99,1,12.999,142.989
68,1069,02-04-2024,Daniel Brown,02-08-2024,NaN,4,7.996,87.956
69,1070,02-04-2024,Jennifer Hernandez,02-07-2024,149.99,1,14.999,164.989

In [27]:
d_frame.describe()

          Order No  Retail Price (USD)  Order Quantity  Tax (USD)  Total (USD)
count    70.000000           67.000000       70.000000  70.000000    68.000000
mean   1035.500000           87.154179        2.400000  14.097600   155.915456
std      20.351085           56.777235        1.334058   3.894425    42.667596
min    1001.000000           19.990000        1.000000   2.999000    32.989000
25%    1018.250000           39.990000        1.000000  12.247500   140.233500
50%    1035.500000           69.990000        2.000000  14.995000   164.945000
75%    1052.750000          129.990000        3.000000  14.999000   164.989000
max    1070.000000          199.990000        5.000000  29.997000   329.967000

In [28]:
d_frame.isnull().sum()

Order No              0
Order Date            0
Customer Name         0
Ship Date             0
Retail Price (USD)    3
Order Quantity        0
Tax (USD)             0
Total (USD)           2
dtype: int64

## Filling Missing values with the mean of the column

In [30]:
d_frame['Retail_PricefillNA'] = d_frame['Retail Price (USD)'].fillna(d_frame['Retail Price (USD)'].mean())

In [35]:
d_frame.head()

,Order No,Order Date,Customer Name,Date,Retail Price (USD),Order Quantity,Tax (USD),Total (USD),Retail_PricefillNA
0,1001,01-01-2024,John Smith,01-03-2024,49.99,2,9.998,109.978,49.99
1,1002,01-01-2024,Jane Doe,01-04-2024,29.99,1,2.999,32.989,29.99
2,1003,01-02-2024,Michael Johnson,01-07-2024,99.99,3,29.997,329.967,99.99
3,1004,01-02-2024,Emily Brown,01-03-2024,19.99,4,7.996,87.956,19.99
4,1005,01-03-2024,David Wilson,01-08-2024,149.99,1,14.999,164.989,149.99

In [32]:
d_frame.dtypes

Order No                int64
Order Date             object
Customer Name          object
Ship Date              object
Retail Price (USD)    float64
Order Quantity          int64
Tax (USD)             float64
Total (USD)           float64
Retail_PricefillNA    float64
dtype: object

## Rename Columns

In [36]:
d_frame = d_frame.rename(columns={'Date':'Ship Date'})
d_frame.head()

,Order No,Order Date,Customer Name,Ship Date,Retail Price (USD),Order Quantity,Tax (USD),Total (USD),Retail_PricefillNA
0,1001,01-01-2024,John Smith,01-03-2024,49.99,2,9.998,109.978,49.99
1,1002,01-01-2024,Jane Doe,01-04-2024,29.99,1,2.999,32.989,29.99
2,1003,01-02-2024,Michael Johnson,01-07-2024,99.99,3,29.997,329.967,99.99
3,1004,01-02-2024,Emily Brown,01-03-2024,19.99,4,7.996,87.956,19.99
4,1005,01-03-2024,David Wilson,01-08-2024,149.99,1,14.999,164.989,149.99

## Change Data Type

In [37]:
d_frame['Tax_new'] = d_frame['Tax (USD)'].astype(int)
d_frame.head()

,Order No,Order Date,Customer Name,Ship Date,Retail Price (USD),Order Quantity,Tax (USD),Total (USD),Retail_PricefillNA,Tax_new
0,1001,01-01-2024,John Smith,01-03-2024,49.99,2,9.998,109.978,49.99,9
1,1002,01-01-2024,Jane Doe,01-04-2024,29.99,1,2.999,32.989,29.99,2
2,1003,01-02-2024,Michael Johnson,01-07-2024,99.99,3,29.997,329.967,99.99,29
3,1004,01-02-2024,Emily Brown,01-03-2024,19.99,4,7.996,87.956,19.99,7
4,1005,01-03-2024,David Wilson,01-08-2024,149.99,1,14.999,164.989,149.99,14

In [38]:
d_frame['New Price'] = d_frame['Retail Price (USD)'].apply(lambda x:x*2)
d_frame.head()

,Order No,Order Date,Customer Name,Ship Date,Retail Price (USD),Order Quantity,Tax (USD),Total (USD),Retail_PricefillNA,Tax_new,New Price
0,1001,01-01-2024,John Smith,01-03-2024,49.99,2,9.998,109.978,49.99,9,99.98
1,1002,01-01-2024,Jane Doe,01-04-2024,29.99,1,2.999,32.989,29.99,2,59.98
2,1003,01-02-2024,Michael Johnson,01-07-2024,99.99,3,29.997,329.967,99.99,29,199.98
3,1004,01-02-2024,Emily Brown,01-03-2024,19.99,4,7.996,87.956,19.99,7,39.98
4,1005,01-03-2024,David Wilson,01-08-2024,149.99,1,14.999,164.989,149.99,14,299.98

## Data Aggregating And Grouping

In [39]:
d_frame.head()

,Order No,Order Date,Customer Name,Ship Date,Retail Price (USD),Order Quantity,Tax (USD),Total (USD),Retail_PricefillNA,Tax_new,New Price
0,1001,01-01-2024,John Smith,01-03-2024,49.99,2,9.998,109.978,49.99,9,99.98
1,1002,01-01-2024,Jane Doe,01-04-2024,29.99,1,2.999,32.989,29.99,2,59.98
2,1003,01-02-2024,Michael Johnson,01-07-2024,99.99,3,29.997,329.967,99.99,29,199.98
3,1004,01-02-2024,Emily Brown,01-03-2024,19.99,4,7.996,87.956,19.99,7,39.98
4,1005,01-03-2024,David Wilson,01-08-2024,149.99,1,14.999,164.989,149.99,14,299.98

In [42]:
group_mean = d_frame.groupby('Customer Name')['Retail Price (USD)'].mean()
print(group_mean)

Customer Name
Amanda Martinez          149.990000
Amy Hernandez             49.990000
Christopher Rodriguez    129.990000
Christopher Thomas        89.990000
Daniel Brown              69.990000
Daniel Davis             199.990000
Daniel Hernandez          94.990000
Daniel Martinez           39.990000
Daniel Smith             199.990000
Daniel Wilson             29.990000
David Brown               19.990000
David Martinez            79.990000
David Rodriguez           49.990000
David Wilson             143.323333
Emily Brown               44.990000
Emily Davis              199.990000
Emily Johnson            139.990000
Emily Rodriguez           39.990000
James Johnson             69.990000
Jane Doe                  29.990000
Jennifer Davis            99.990000
Jennifer Hernandez        94.990000
Jennifer Martinez         79.990000
Jennifer Smith            29.990000
Jessica Gonzalez         129.990000
Jessica Johnson          129.990000
Jessica Martinez          34.990000
Jessica Smith             29.990000
Jessica Wilson           139.990000
John Smith                49.990000
Kimberly Garcia          199.990000
Laura Brown               39.990000
Lisa Taylor               79.990000
Matthew Garcia           139.990000
Matthew Hernandez         69.990000
Matthew Johnson           39.990000
Matthew Smith             34.990000
Matthew Wilson            19.990000
Melissa Lopez             79.990000
Michael Davis            199.990000
Michael Garcia            79.990000
Michael Johnson           89.990000
Michael Martinez          34.990000
Michael Smith             49.990000
Richard Perez             49.990000
Sarah Anderson            69.990000
Sarah Garcia             149.990000
Sarah Gonzalez           104.990000
Sarah Johnson             34.990000
Sarah Smith               69.990000
William Hernandez         29.990000
Name: Retail Price (USD), dtype: float64

In [44]:
group_sum = d_frame.groupby(['Order No','Order Quantity'])['Total (USD)'].sum()
print(group_sum)

Order No  Order Quantity
1001      2                 109.978
1002      1                  32.989
1003      3                 329.967
1004      4                  87.956
1005      1                 164.989
                             ...
1066      2                 175.978
1067      3                 164.967
1068      1                 142.989
1069      4                  87.956
1070      1                 164.989
Name: Total (USD), Length: 70, dtype: float64

## Aggregate mupltiple functions

In [47]:
grouped_agg = d_frame.groupby('Order Quantity')['Total (USD)'].agg(['mean','sum','count'])

grouped_agg

                   mean       sum  count
Order Quantity
1               166.364  3992.736     24
2               162.228  2595.648     16
3               160.567  2408.505     15
4                87.956   615.692      7
5               164.945   989.670      6

## Merging And Joining Data Frames

In [48]:
# Create some sample data frames

df1 = pd.DataFrame({'Key':['A','B','C'] , 'Value1' : [1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'] , 'Value2' : [4,5,6]})

df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [49]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [50]:
## Merge This data frame on the 'Key Coulums'

pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [51]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [52]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [53]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6